// <auto-generated>
//     Generated from tools/catalog.py. Every winget id in this file was checked
//     against the official winget source index before being committed.
//     Do not edit by hand: regenerate with `python3 tools/gen_catalog.py`.
// </auto-generated>

using System.Collections.Generic;

namespace HyperionWPF.Model
{
    internal static partial class Catalog
    {
        private static IReadOnlyList<Category> BuildCategories() => new[]
        {
            new Category("Browsers", "Browsers", "Браузеры", CategoryGlyph.Browser, new[]
            {
                new AppEntry("Chrome", "Google Chrome", "Chrome", "Fast and secure browser by Google", "Быстрый и безопасный браузер от Google", new PackageRef("Google.Chrome", "googlechrome", "googlechrome")),
                new AppEntry("Firefox", "Mozilla Firefox", "Firefox", "Independent browser focused on privacy", "Независимый браузер с упором на приватность", new PackageRef("Mozilla.Firefox", "firefox", "firefox")),
                new AppEntry("Edge", "Microsoft Edge", "Edge", "Chromium browser built into Windows", "Chromium-браузер, встроенный в Windows", new PackageRef("Microsoft.Edge", null, "microsoft-edge")),
                new AppEntry("Brave", "Brave", "Brave", "Chromium browser with ad and tracker blocking", "Chromium-браузер со встроенной блокировкой рекламы", new PackageRef("Brave.Brave", "brave", "brave")),
                new AppEntry("Opera", "Opera", "Opera", "Browser with built-in VPN and messengers", "Браузер со встроенным VPN и мессенджерами", new PackageRef("Opera.Opera", "opera", "opera")),
                new AppEntry("Vivaldi", "Vivaldi", null, "Highly customisable browser for power users", "Гибко настраиваемый браузер для опытных пользователей", new PackageRef("Vivaldi.Vivaldi", "vivaldi", "vivaldi")),
                new AppEntry("Yandex_Browser", "Yandex Browser", null, "Browser by Yandex with Alice assistant", "Браузер Яндекса с голосовым помощником Алисой", new PackageRef("Yandex.Browser", null, "yandex-browser")),
                new AppEntry("Zen_Browser", "Zen Browser", null, "Firefox-based browser with a calm, tidy UI", "Браузер на базе Firefox со спокойным минималистичным интерфейсом", new PackageRef("Zen-Team.Zen-Browser", null, null)),
                new AppEntry("Tor_Browser", "Tor Browser", null, "Anonymous browsing through the Tor network", "Анонимный просмотр сайтов через сеть Tor", new PackageRef("TorProject.TorBrowser", "tor-browser", "tor-browser")),
            }),
            new Category("Messaging", "Messaging", "Мессенджеры", CategoryGlyph.Chat, new[]
            {
                new AppEntry("Telegram", "Telegram", "Telegram", "Fast cloud messenger with huge groups", "Быстрый облачный мессенджер с большими группами", new PackageRef("Telegram.TelegramDesktop", "telegram", "telegram")),
                new AppEntry("Discord", "Discord", "Discord", "Voice, video and text chat for communities", "Голосовой, видео- и текстовый чат для сообществ", new PackageRef("Discord.Discord", "discord", "discord")),
                new AppEntry("Signal", "Signal", null, "End-to-end encrypted private messenger", "Мессенджер со сквозным шифрованием", new PackageRef("OpenWhisperSystems.Signal", "signal", "signal")),
                new AppEntry("Viber", "Viber", null, "Messenger with calls to mobile numbers", "Мессенджер со звонками на мобильные номера", new PackageRef("Rakuten.Viber", null, "viber")),
                new AppEntry("Slack", "Slack", null, "Team chat with channels and integrations", "Рабочий чат с каналами и интеграциями", new PackageRef("SlackTechnologies.Slack", "slack", "slack")),
                new AppEntry("Teams", "Microsoft Teams", "Teams", "Meetings and collaboration by Microsoft", "Встречи и совместная работа от Microsoft", new PackageRef("Microsoft.Teams", null, "microsoft-teams")),
                new AppEntry("Zoom", "Zoom", "Zoom", "Video conferencing and webinars", "Видеоконференции и вебинары", new PackageRef("Zoom.Zoom", "zoom", "zoom")),
                new AppEntry("Element", "Element", null, "Matrix client for decentralised chat", "Клиент Matrix для децентрализованных чатов", new PackageRef("Element.Element", null, "element-desktop")),
            }),
            new Category("Media", "Media", "Мультимедиа", CategoryGlyph.Media, new[]
            {
                new AppEntry("VLC", "VLC media player", "VLC", "Plays practically every audio and video format", "Проигрывает практически любые аудио и видео", new PackageRef("VideoLAN.VLC", "vlc", "vlc")),
                new AppEntry("Spotify", "Spotify", "Spotify", "Music and podcast streaming", "Стриминг музыки и подкастов", new PackageRef("Spotify.Spotify", "spotify", "spotify")),
                new AppEntry("AIMP", "AIMP", null, "Lightweight audio player with an equaliser", "Лёгкий аудиоплеер с эквалайзером", new PackageRef("AIMP.AIMP", "aimp", "aimp")),
                new AppEntry("foobar2000", "foobar2000", null, "Minimal, highly configurable audio player", "Минималистичный и гибкий аудиоплеер", new PackageRef("PeterPawlowski.foobar2000", "foobar2000", "foobar2000")),
                new AppEntry("MPV", "mpv", null, "Keyboard-driven video player with no clutter", "Видеоплеер без лишнего интерфейса", new PackageRef("shinchiro.mpv", "mpv", "mpv.install")),
                new AppEntry("K_Lite", "K-Lite Codec Pack", null, "Codec pack for system-wide video playback", "Набор кодеков для воспроизведения видео в системе", new PackageRef("CodecGuide.K-LiteCodecPack.Standard", null, "k-litecodecpackstandard")),
                new AppEntry("OBS_Studio", "OBS Studio", null, "Screen recording and live streaming", "Запись экрана и трансляции", new PackageRef("OBSProject.OBSStudio", null, "obs-studio")),
                new AppEntry("Audacity", "Audacity", "Audacity", "Free multi-track audio editor", "Бесплатный многодорожечный аудиоредактор", new PackageRef("Audacity.Audacity", "audacity", "audacity")),
                new AppEntry("HandBrake", "HandBrake", "HandBrake", "Video converter with ready-made presets", "Видеоконвертер с готовыми пресетами", new PackageRef("HandBrake.HandBrake", "handbrake", "handbrake")),
                new AppEntry("Shotcut", "Shotcut", null, "Free cross-platform video editor", "Бесплатный видеоредактор", new PackageRef("Meltytech.Shotcut", "shotcut", "shotcut")),
            }),
            new Category("Graphics", "Graphics", "Графика и дизайн", CategoryGlyph.Image, new[]
            {
                new AppEntry("Krita", "Krita", "Krita", "Digital painting studio for artists", "Студия цифровой живописи для художников", new PackageRef("KDE.Krita", "krita", "krita")),
                new AppEntry("GIMP", "GIMP", "GIMP", "Full-featured raster image editor", "Полноценный редактор растровой графики", new PackageRef("GIMP.GIMP", "gimp", "gimp")),
                new AppEntry("Inkscape", "Inkscape", "Inkscape", "Vector graphics editor for SVG", "Редактор векторной графики SVG", new PackageRef("Inkscape.Inkscape", "inkscape", "inkscape")),
                new AppEntry("Paint_NET", "paint.net", null, "Simple image editor with layers", "Простой редактор изображений со слоями", new PackageRef("dotPDN.PaintDotNet", "paint.net", "paint.net")),
                new AppEntry("Blender", "Blender", "Blender", "3D modelling, animation and rendering", "3D-моделирование, анимация и рендеринг", new PackageRef("BlenderFoundation.Blender", "blender", "blender")),
                new AppEntry("Figma", "Figma", null, "Collaborative interface design", "Совместное проектирование интерфейсов", new PackageRef("Figma.Figma", null, "figma")),
                new AppEntry("IrfanView", "IrfanView", "IrfanView", "Very fast image viewer and converter", "Очень быстрый просмотрщик и конвертер изображений", new PackageRef("IrfanSkiljan.IrfanView", "irfanview", "irfanview")),
                new AppEntry("XnView_MP", "XnView MP", null, "Image browser supporting 500+ formats", "Просмотрщик с поддержкой 500+ форматов", new PackageRef("XnSoft.XnViewMP", "xnviewmp", "xnviewmp")),
                new AppEntry("ShareX", "ShareX", "ShareX", "Screenshots and screen recording with upload", "Скриншоты и запись экрана с загрузкой в сеть", new PackageRef("ShareX.ShareX", "sharex", "sharex")),
                new AppEntry("Greenshot", "Greenshot", "Greenshot", "Lightweight screenshot tool with an editor", "Лёгкий инструмент для скриншотов с редактором", new PackageRef("Greenshot.Greenshot", "greenshot", "greenshot")),
                new AppEntry("Lightshot", "Lightshot", null, "Instant screenshots of any screen area", "Мгновенные скриншоты любой области экрана", new PackageRef("Skillbrains.Lightshot", null, "lightshot")),
            }),
            new Category("Documents", "Documents", "Документы", CategoryGlyph.Doc, new[]
            {
                new AppEntry("LibreOffice", "LibreOffice", null, "Free office suite: text, sheets, slides", "Бесплатный офис: текст, таблицы, презентации", new PackageRef("TheDocumentFoundation.LibreOffice", "libreoffice", "libreoffice-fresh")),
                new AppEntry("ONLYOFFICE", "ONLYOFFICE", null, "Office suite with strong MS Office fidelity", "Офисный пакет с хорошей совместимостью с MS Office", new PackageRef("ONLYOFFICE.DesktopEditors", null, "onlyoffice")),
                new AppEntry("Acrobat_Reader", "Adobe Acrobat Reader", null, "The reference PDF reader", "Эталонный просмотрщик PDF", new PackageRef("Adobe.Acrobat.Reader.64-bit", null, "adobereader")),
                new AppEntry("Foxit_Reader", "Foxit Reader", "Foxit_Reader", "Fast PDF reader with annotations", "Быстрый просмотрщик PDF с аннотациями", new PackageRef("Foxit.FoxitReader", "foxit-reader", "foxitreader")),
                new AppEntry("SumatraPDF", "SumatraPDF", "SumatraPDF", "Tiny reader for PDF, EPUB and comics", "Крошечная читалка PDF, EPUB и комиксов", new PackageRef("SumatraPDF.SumatraPDF", "sumatrapdf", "sumatrapdf")),
                new AppEntry("PDF24", "PDF24 Creator", null, "Merge, split and convert PDF files", "Объединение, разделение и конвертация PDF", new PackageRef("geeksoftwareGmbH.PDF24Creator", null, "pdf24")),
                new AppEntry("Obsidian", "Obsidian", null, "Markdown notes stored as local files", "Заметки в Markdown, хранящиеся локально", new PackageRef("Obsidian.Obsidian", "obsidian", "obsidian")),
                new AppEntry("Notion", "Notion", null, "Notes, wiki and tasks in one workspace", "Заметки, вики и задачи в одном месте", new PackageRef("Notion.Notion", "notion", "notion")),
                new AppEntry("Evernote", "Evernote", "Evernote", "Notes, web clippings and reminders", "Заметки, вырезки из веба и напоминания", new PackageRef("Evernote.Evernote", "evernote", "evernote")),
                new AppEntry("Calibre", "calibre", null, "E-book library manager and converter", "Менеджер и конвертер электронных книг", new PackageRef("calibre.calibre", "calibre", "calibre")),
                new AppEntry("Anki", "Anki", null, "Spaced-repetition flashcards", "Карточки для запоминания по интервальному методу", new PackageRef("Anki.Anki", "anki", "anki")),
            }),
            new Category("Gaming", "Gaming", "Игры", CategoryGlyph.Game, new[]
            {
                new AppEntry("Steam", "Steam", "Steam", "The biggest PC game store and launcher", "Крупнейший магазин и лаунчер игр для ПК", new PackageRef("Valve.Steam", "steam", "steam")),
                new AppEntry("Epic_Games", "Epic Games", "Epic_Games", "Epic store with weekly free games", "Магазин Epic с еженедельными бесплатными играми", new PackageRef("EpicGames.EpicGamesLauncher", "epic-games-launcher", "epicgameslauncher")),
                new AppEntry("EA_App", "EA App", "EA_App", "Launcher for Electronic Arts games", "Лаунчер для игр Electronic Arts", new PackageRef("ElectronicArts.EADesktop", null, "ea-app")),
                new AppEntry("GOG_Galaxy", "GOG Galaxy", "GOG_Galaxy", "DRM-free store that unifies your libraries", "Магазин без DRM, объединяющий библиотеки", new PackageRef("GOG.Galaxy", null, "goggalaxy")),
                new AppEntry("Ubisoft_Connect", "Ubisoft Connect", null, "Launcher for Ubisoft games", "Лаунчер для игр Ubisoft", new PackageRef("Ubisoft.Connect", null, "ubisoft-connect")),
                new AppEntry("Battle_net", "Battle.net", null, "Launcher for Blizzard games", "Лаунчер для игр Blizzard", new PackageRef("Blizzard.BattleNet", null, "battle.net")),
                new AppEntry("MSI_Afterburner", "MSI Afterburner", null, "GPU tuning and in-game monitoring", "Разгон видеокарты и мониторинг в играх", new PackageRef("Guru3D.Afterburner", null, "msiafterburner")),
            }),
            new Category("Files", "Files", "Файлы и облако", CategoryGlyph.Cloud, new[]
            {
                new AppEntry("qBittorrent", "qBittorrent", "qBittorrent", "Ad-free torrent client", "Торрент-клиент без рекламы", new PackageRef("qBittorrent.qBittorrent", "qbittorrent", "qbittorrent")),
                new AppEntry("Google_Drive", "Google Drive", "Google_Drive", "Google cloud storage with desktop sync", "Облако Google с синхронизацией на ПК", new PackageRef("Google.GoogleDrive", "googledrive", "googledrive")),
                new AppEntry("OneDrive", "OneDrive", "OneDrive", "Microsoft cloud storage", "Облачное хранилище Microsoft", new PackageRef("Microsoft.OneDrive", null, "onedrive")),
                new AppEntry("Dropbox", "Dropbox", "Dropbox", "Classic file sync across devices", "Классическая синхронизация файлов между устройствами", new PackageRef("Dropbox.Dropbox", "dropbox", "dropbox")),
                new AppEntry("Yandex_Disk", "Yandex.Disk", null, "Yandex cloud storage", "Облачное хранилище Яндекса", new PackageRef("Yandex.Disk", null, "yandex-disk")),
                new AppEntry("Quick_Share", "Quick Share", "Quick_Share", "Send files between Windows and Android", "Передача файлов между Windows и Android", new PackageRef("Google.QuickShare", null, null)),
                new AppEntry("Total_Commander", "Total Commander", null, "Two-pane file manager, the classic", "Классический двухпанельный файловый менеджер", new PackageRef("Ghisler.TotalCommander", null, "totalcommander")),
                new AppEntry("FileZilla", "FileZilla", "FileZilla", "FTP, FTPS and SFTP client", "Клиент FTP, FTPS и SFTP", new PackageRef(null, "filezilla", "filezilla")),
                new AppEntry("WinSCP", "WinSCP", "WinSCP", "SFTP/SCP transfers with a dual-pane UI", "Передача по SFTP/SCP в двухпанельном окне", new PackageRef("WinSCP.WinSCP", "winscp", "winscp")),
                new AppEntry("Cyberduck", "Cyberduck", null, "Browse cloud and FTP storage like folders", "Доступ к облакам и FTP как к папкам", new PackageRef("Iterate.Cyberduck", null, "cyberduck")),
            }),
            new Category("Utilities", "Utilities", "Утилиты", CategoryGlyph.Tools, new[]
            {
                new AppEntry("Everything", "Everything", "Everything", "Instant file search by name", "Мгновенный поиск файлов по имени", new PackageRef("voidtools.Everything", "everything", "everything")),
                new AppEntry("PowerToys", "Microsoft PowerToys", null, "Window, launcher and utility pack for Windows", "Набор утилит для окон, поиска и не только", new PackageRef("Microsoft.PowerToys", null, "powertoys")),
                new AppEntry("Windows_Terminal", "Windows Terminal", null, "Modern tabbed terminal for Windows", "Современный терминал с вкладками", new PackageRef("Microsoft.WindowsTerminal", null, "microsoft-windows-terminal")),
                new AppEntry("TeamViewer", "TeamViewer", "TeamViewer", "Remote access and support", "Удалённый доступ и поддержка", new PackageRef("TeamViewer.TeamViewer", "teamviewer", "teamviewer")),
                new AppEntry("AnyDesk", "AnyDesk", null, "Lightweight, low-latency remote desktop", "Лёгкий удалённый рабочий стол с низкой задержкой", new PackageRef("AnyDesk.AnyDesk", "anydesk", "anydesk")),
                new AppEntry("RealVNC", "RealVNC", "RealVNC_Server", "Remote desktop over the VNC protocol", "Удалённый рабочий стол по протоколу VNC", new[]
                {
                    new AppVariant("Server", new PackageRef("RealVNC.VNCServer", null, "vnc-server")),
                    new AppVariant("Viewer", new PackageRef("RealVNC.VNCViewer", "vnc-viewer", "vnc-viewer")),
                }),
                new AppEntry("TightVNC", "TightVNC", "TightVNC", "Free VNC server and viewer", "Бесплатный VNC-сервер и клиент", new PackageRef("GlavSoft.TightVNC", "tightvnc", "tightvnc")),
                new AppEntry("TeraCopy", "TeraCopy", "TeraCopy", "Faster file copying with verification", "Быстрое копирование файлов с проверкой", new PackageRef("CodeSector.TeraCopy", "teracopy", "teracopy")),
                new AppEntry("Revo", "Revo Uninstaller", "Revo", "Uninstall programs and clean the leftovers", "Удаление программ вместе с их следами", new PackageRef("RevoUninstaller.RevoUninstaller", "revo-uninstaller", "revo-uninstaller")),
                new AppEntry("WizTree", "WizTree", "WizTree", "Find what fills your disk in seconds", "Находит, что занимает диск, за секунды", new PackageRef("AntibodySoftware.WizTree", "wiztree", "wiztree")),
                new AppEntry("CCleaner", "CCleaner", "CCleaner", "Clean temporary files and the registry", "Очистка временных файлов и реестра", new PackageRef("Piriform.CCleaner", "ccleaner", "ccleaner")),
                new AppEntry("Rufus", "Rufus", null, "Make bootable USB drives", "Создание загрузочных USB-накопителей", new PackageRef("Rufus.Rufus", "rufus", "rufus")),
                new AppEntry("Ditto", "Ditto", null, "Clipboard history manager", "Менеджер истории буфера обмена", new PackageRef("Ditto.Ditto", "ditto", "ditto")),
                new AppEntry("CrystalDiskInfo", "CrystalDiskInfo", null, "S.M.A.R.T. health monitoring for drives", "Мониторинг здоровья дисков по S.M.A.R.T.", new PackageRef("CrystalDewWorld.CrystalDiskInfo", "crystaldiskinfo", "crystaldiskinfo")),
                new AppEntry("HWiNFO", "HWiNFO", null, "Detailed hardware info and sensors", "Подробная информация о железе и датчиках", new PackageRef("REALiX.HWiNFO", "hwinfo", "hwinfo")),
                new AppEntry("CPU_Z", "CPU-Z", null, "CPU, memory and board identification", "Определение процессора, памяти и платы", new PackageRef("CPUID.CPU-Z", "cpu-z", "cpu-z")),
            }),
            new Category("Compression", "Compression", "Архиваторы", CategoryGlyph.Archive, new[]
            {
                new AppEntry("7-Zip", "7-Zip", "7-Zip", "Free archiver with the best compression", "Бесплатный архиватор с лучшим сжатием", new PackageRef("7zip.7zip", "7zip", "7zip")),
                new AppEntry("NanaZip", "NanaZip", null, "Modern 7-Zip fork with Windows 11 menus", "Современный форк 7-Zip с меню Windows 11", new PackageRef("M2Team.NanaZip", null, "nanazip")),
                new AppEntry("WinRAR", "WinRAR", "WinRAR", "The RAR format archiver", "Архиватор формата RAR", new PackageRef("RARLab.WinRAR", null, "winrar")),
                new AppEntry("PeaZip", "PeaZip", null, "Open-source archiver with strong encryption", "Открытый архиватор с надёжным шифрованием", new PackageRef("Giorgiotani.Peazip", "peazip", "peazip")),
            }),
            new Category("Security", "Security", "Безопасность", CategoryGlyph.Shield, new[]
            {
                new AppEntry("Bitwarden", "Bitwarden", null, "Password manager with cloud sync", "Менеджер паролей с облачной синхронизацией", new PackageRef("Bitwarden.Bitwarden", "bitwarden", "bitwarden")),
                new AppEntry("KeePassXC", "KeePassXC", null, "Offline password vault in a local file", "Офлайн-хранилище паролей в локальном файле", new PackageRef("KeePassXCTeam.KeePassXC", "keepassxc", "keepassxc")),
                new AppEntry("KeePass_2", "KeePass 2", "KeePass_2", "The original KeePass password manager", "Оригинальный менеджер паролей KeePass", new PackageRef("DominikReichl.KeePass", "keepass", "keepass")),
                new AppEntry("Malwarebytes", "Malwarebytes", "Malwarebytes", "On-demand malware scanner and cleaner", "Сканер и чистильщик вредоносного ПО", new PackageRef("Malwarebytes.Malwarebytes", null, "malwarebytes")),
                new AppEntry("Proton_VPN", "Proton VPN", null, "VPN with an audited no-logs policy", "VPN с проверенной политикой отсутствия логов", new PackageRef("Proton.ProtonVPN", null, "protonvpn")),
            }),
            new Category("Developer Tools", "Developer Tools", "Для разработчиков", CategoryGlyph.Code, new[]
            {
                new AppEntry("Visual_Studio_Code", "Visual Studio Code", "Visual_Studio_Code", "The most popular extensible code editor", "Самый популярный расширяемый редактор кода", new PackageRef("Microsoft.VisualStudioCode", "vscode", "vscode")),
                new AppEntry("Cursor", "Cursor", "Cursor", "AI-first code editor built on VS Code", "AI-редактор кода на базе VS Code", new PackageRef("Anysphere.Cursor", "cursor", null)),
                new AppEntry("Notepad++", "Notepad++", "Notepad__", "Lightweight editor for quick edits", "Лёгкий редактор для быстрых правок", new PackageRef("Notepad++.Notepad++", "notepadplusplus", "notepadplusplus")),
                new AppEntry("Sublime_Text", "Sublime Text", null, "Very fast editor with multiple cursors", "Очень быстрый редактор с мультикурсором", new PackageRef("SublimeHQ.SublimeText.4", "sublime-text", "sublimetext4")),
                new AppEntry("Git", "Git", "Git", "The version control system", "Система контроля версий", new PackageRef("Git.Git", "git", "git")),
                new AppEntry("GitHub_Desktop", "GitHub Desktop", null, "Visual Git client for GitHub", "Визуальный Git-клиент для GitHub", new PackageRef("GitHub.GitHubDesktop", null, "github-desktop")),
                new AppEntry("Python_3", "Python 3", "Python_3", "Python interpreter and pip", "Интерпретатор Python и pip", new PackageRef("Python.Python.3.13", "python", "python3")),
                new AppEntry("NodeJS", "Node.js LTS", null, "JavaScript runtime with npm", "Среда выполнения JavaScript с npm", new PackageRef("OpenJS.NodeJS.LTS", "nodejs-lts", "nodejs-lts")),
                new AppEntry("PowerShell_7", "PowerShell 7", null, "Cross-platform PowerShell, the modern one", "Современный кроссплатформенный PowerShell", new PackageRef("Microsoft.PowerShell", "pwsh", "powershell-core")),
                new AppEntry("Docker_Desktop", "Docker Desktop", null, "Containers on Windows via WSL 2", "Контейнеры в Windows через WSL 2", new PackageRef("Docker.DockerDesktop", null, "docker-desktop")),
                new AppEntry("DBeaver", "DBeaver", null, "Universal database client", "Универсальный клиент баз данных", new PackageRef("DBeaver.DBeaver.Community", "dbeaver", "dbeaver")),
                new AppEntry("Postman", "Postman", null, "API testing and collections", "Тестирование API и коллекции запросов", new PackageRef("Postman.Postman", "postman", "postman")),
                new AppEntry("PuTTY", "PuTTY", "PuTTY", "The classic SSH and serial client", "Классический SSH- и serial-клиент", new PackageRef("PuTTY.PuTTY", "putty", "putty")),
                new AppEntry("WinMerge", "WinMerge", "WinMerge", "Compare and merge files and folders", "Сравнение и слияние файлов и папок", new PackageRef("WinMerge.WinMerge", "winmerge", "winmerge")),
                new AppEntry("Wireshark", "Wireshark", null, "Network protocol analyser", "Анализатор сетевых протоколов", new PackageRef("WiresharkFoundation.Wireshark", null, "wireshark")),
                new AppEntry("VirtualBox", "Oracle VirtualBox", null, "Free desktop virtualisation", "Бесплатная виртуализация на ПК", new PackageRef("Oracle.VirtualBox", null, "virtualbox")),
            }),
            new Category(".NET", ".NET", ".NET", CategoryGlyph.Runtime, new[]
            {
                new AppEntry(".NET_Desktop_Runtime", ".NET Desktop Runtime", null, "Runtime required by WPF and WinForms apps", "Среда выполнения для приложений WPF и WinForms", new[]
                {
                    new AppVariant("8 (x64)", new PackageRef("Microsoft.DotNet.DesktopRuntime.8", null, "dotnet-8.0-desktopruntime")),
                    new AppVariant("9 (x64)", new PackageRef("Microsoft.DotNet.DesktopRuntime.9", null, "dotnet-9.0-desktopruntime")),
                    new AppVariant("10 (x64)", new PackageRef("Microsoft.DotNet.DesktopRuntime.10", null, "dotnet-10.0-desktopruntime")),
                }),
                new AppEntry("ASP.NET_Core_Runtime", "ASP.NET Core Runtime", null, "Runtime required by ASP.NET Core web apps", "Среда выполнения для веб-приложений ASP.NET Core", new[]
                {
                    new AppVariant("8 (x64)", new PackageRef("Microsoft.DotNet.AspNetCore.8", null, "dotnet-8.0-aspnetruntime")),
                    new AppVariant("9 (x64)", new PackageRef("Microsoft.DotNet.AspNetCore.9", null, "dotnet-9.0-aspnetruntime")),
                    new AppVariant("10 (x64)", new PackageRef("Microsoft.DotNet.AspNetCore.10", null, "dotnet-10.0-aspnetruntime")),
                }),
                new AppEntry(".NET_SDK", ".NET SDK", null, "Full SDK for building .NET applications", "Полный SDK для разработки приложений .NET", new[]
                {
                    new AppVariant("8", new PackageRef("Microsoft.DotNet.SDK.8", null, "dotnet-8.0-sdk")),
                    new AppVariant("9", new PackageRef("Microsoft.DotNet.SDK.9", null, "dotnet-9.0-sdk")),
                    new AppVariant("10", new PackageRef("Microsoft.DotNet.SDK.10", null, "dotnet-10.0-sdk")),
                }),
                new AppEntry(".NET_Framework_4.8.1", ".NET Framework 4.8.1 Dev Pack", null, "Targeting pack for building .NET Framework apps", "Пакет разработки под .NET Framework", new PackageRef("Microsoft.DotNet.Framework.DeveloperPack_4", null, "netfx-4.8.1-devpack")),
            }),
            new Category("Java", "Java", "Java", CategoryGlyph.Runtime, new[]
            {
                new AppEntry("Temurin_JRE", "Eclipse Temurin JRE", "Java__AdoptOpenJDK__8", "Free Java runtime for desktop apps", "Бесплатная среда выполнения Java для программ", new[]
                {
                    new AppVariant("8 (x64)", new PackageRef("EclipseAdoptium.Temurin.8.JRE", "temurin8-jre", "temurin8jre")),
                    new AppVariant("11 (x64)", new PackageRef("EclipseAdoptium.Temurin.11.JRE", "temurin11-jre", "temurin11jre")),
                    new AppVariant("17 (x64)", new PackageRef("EclipseAdoptium.Temurin.17.JRE", "temurin17-jre", "temurin17jre")),
                    new AppVariant("21 (x64)", new PackageRef("EclipseAdoptium.Temurin.21.JRE", "temurin21-jre", "temurin21jre")),
                }),
                new AppEntry("Corretto_JDK", "Amazon Corretto JDK", "JDK__Amazon_Corretto__8", "Amazon's supported OpenJDK build", "Сборка OpenJDK с поддержкой от Amazon", new[]
                {
                    new AppVariant("8 (x64)", new PackageRef("Amazon.Corretto.8.JDK", "corretto8-jdk", "corretto8jdk")),
                    new AppVariant("11 (x64)", new PackageRef("Amazon.Corretto.11.JDK", "corretto11-jdk", "corretto11jdk")),
                    new AppVariant("17 (x64)", new PackageRef("Amazon.Corretto.17.JDK", "corretto17-jdk", "corretto17jdk")),
                    new AppVariant("21 (x64)", new PackageRef("Amazon.Corretto.21.JDK", "corretto21-jdk", "corretto21jdk")),
                }),
                new AppEntry("Microsoft_OpenJDK", "Microsoft Build of OpenJDK", "Java__AdoptOpenJDK__8", "Microsoft's OpenJDK build with Hotspot", "Сборка OpenJDK от Microsoft с Hotspot", new[]
                {
                    new AppVariant("17", new PackageRef("Microsoft.OpenJDK.17", null, "microsoft-openjdk17")),
                    new AppVariant("21", new PackageRef("Microsoft.OpenJDK.21", null, "microsoft-openjdk21")),
                }),
            }),
            new Category("VC++ Redistributables", "VC++ Redistributables", "Библиотеки VC++", CategoryGlyph.Runtime, new[]
            {
                new AppEntry("VC_Redist_2015_", "Visual C++ 2015-2022", "VC_Redist_x64_2015_", "Runtime libraries required by most modern apps", "Библиотеки, нужные большинству современных программ", new[]
                {
                    new AppVariant("x64", new PackageRef("Microsoft.VCRedist.2015+.x64", null, "vcredist140")),
                    new AppVariant("x86", new PackageRef("Microsoft.VCRedist.2015+.x86", null, "vcredist140")),
                }),
                new AppEntry("VC_Redist_2013", "Visual C++ 2013", "VC_Redist_x64_2013", "Runtime libraries for older applications", "Библиотеки для более старых программ", new[]
                {
                    new AppVariant("x64", new PackageRef("Microsoft.VCRedist.2013.x64", null, "vcredist2013")),
                    new AppVariant("x86", new PackageRef("Microsoft.VCRedist.2013.x86", null, "vcredist2013")),
                }),
                new AppEntry("VC_Redist_2012", "Visual C++ 2012", "VC_Redist_x64_2012", "Runtime libraries for older applications", "Библиотеки для более старых программ", new[]
                {
                    new AppVariant("x64", new PackageRef("Microsoft.VCRedist.2012.x64", null, "vcredist2012")),
                    new AppVariant("x86", new PackageRef("Microsoft.VCRedist.2012.x86", null, "vcredist2012")),
                }),
                new AppEntry("VC_Redist_2010", "Visual C++ 2010", "VC_Redist_x64_2010", "Runtime libraries for legacy applications", "Библиотеки для устаревших программ", new[]
                {
                    new AppVariant("x64", new PackageRef("Microsoft.VCRedist.2010.x64", null, "vcredist2010")),
                    new AppVariant("x86", new PackageRef("Microsoft.VCRedist.2010.x86", null, "vcredist2010")),
                }),
                new AppEntry("VC_Redist_2008", "Visual C++ 2008", "VC_Redist_x64_2008", "Runtime libraries for legacy applications", "Библиотеки для устаревших программ", new[]
                {
                    new AppVariant("x64", new PackageRef("Microsoft.VCRedist.2008.x64", null, "vcredist2008")),
                    new AppVariant("x86", new PackageRef("Microsoft.VCRedist.2008.x86", null, "vcredist2008")),
                }),
            }),
        };

        private static readonly string[] PopularKeys =
        {
            "Chrome",
            "Firefox",
            "Telegram",
            "Discord",
            "VLC",
            "Spotify",
            "7-Zip",
            "WinRAR",
            "Everything",
            "PowerToys",
            "Steam",
            "qBittorrent",
            "Notepad++",
            "Visual_Studio_Code",
            "Git",
            "Acrobat_Reader",
            "Bitwarden",
            "AnyDesk",
        };

        private static readonly (string Key, string Variant)[] PopularVariants =
        {
            ("VC_Redist_2015_", "x64"),
            (".NET_Desktop_Runtime", "8 (x64)"),
        };
    }
}
