# -*- coding: utf-8 -*-
# Source of truth for the Hyperion catalogue.
# app = (key, title, winget, scoop, choco, desc_en, desc_ru)
# group = (key, title, desc_en, desc_ru, [(variant_label, winget, scoop, choco), ...])

A = lambda key, title, winget, scoop, choco, en, ru: dict(
    kind="app", key=key, title=title, winget=winget, scoop=scoop, choco=choco, en=en, ru=ru)
G = lambda key, title, en, ru, variants: dict(
    kind="group", key=key, title=title, en=en, ru=ru, variants=variants)

CATEGORIES = [
 ("Browsers", "Браузеры", "browser", [
   A("Chrome","Google Chrome","Google.Chrome","googlechrome","googlechrome",
     "Fast and secure browser by Google","Быстрый и безопасный браузер от Google"),
   A("Firefox","Mozilla Firefox","Mozilla.Firefox","firefox","firefox",
     "Independent browser focused on privacy","Независимый браузер с упором на приватность"),
   A("Edge","Microsoft Edge","Microsoft.Edge",None,"microsoft-edge",
     "Chromium browser built into Windows","Chromium-браузер, встроенный в Windows"),
   A("Brave","Brave","Brave.Brave","brave","brave",
     "Chromium browser with ad and tracker blocking","Chromium-браузер со встроенной блокировкой рекламы"),
   A("Opera","Opera","Opera.Opera","opera","opera",
     "Browser with built-in VPN and messengers","Браузер со встроенным VPN и мессенджерами"),
   A("Vivaldi","Vivaldi","Vivaldi.Vivaldi","vivaldi","vivaldi",
     "Highly customisable browser for power users","Гибко настраиваемый браузер для опытных пользователей"),
   A("Yandex_Browser","Yandex Browser","Yandex.Browser",None,"yandex-browser",
     "Browser by Yandex with Alice assistant","Браузер Яндекса с голосовым помощником Алисой"),
   A("Zen_Browser","Zen Browser","Zen-Team.Zen-Browser",None,None,
     "Firefox-based browser with a calm, tidy UI","Браузер на базе Firefox со спокойным минималистичным интерфейсом"),
   A("Tor_Browser","Tor Browser","TorProject.TorBrowser","tor-browser","tor-browser",
     "Anonymous browsing through the Tor network","Анонимный просмотр сайтов через сеть Tor"),
 ]),
 ("Messaging", "Мессенджеры", "chat", [
   A("Telegram","Telegram","Telegram.TelegramDesktop","telegram","telegram",
     "Fast cloud messenger with huge groups","Быстрый облачный мессенджер с большими группами"),
   A("Discord","Discord","Discord.Discord","discord","discord",
     "Voice, video and text chat for communities","Голосовой, видео- и текстовый чат для сообществ"),
   A("Signal","Signal","OpenWhisperSystems.Signal","signal","signal",
     "End-to-end encrypted private messenger","Мессенджер со сквозным шифрованием"),
   A("Viber","Viber","Rakuten.Viber",None,"viber",
     "Messenger with calls to mobile numbers","Мессенджер со звонками на мобильные номера"),
   A("Slack","Slack","SlackTechnologies.Slack","slack","slack",
     "Team chat with channels and integrations","Рабочий чат с каналами и интеграциями"),
   A("Teams","Microsoft Teams","Microsoft.Teams",None,"microsoft-teams",
     "Meetings and collaboration by Microsoft","Встречи и совместная работа от Microsoft"),
   A("Zoom","Zoom","Zoom.Zoom","zoom","zoom",
     "Video conferencing and webinars","Видеоконференции и вебинары"),
   A("Element","Element","Element.Element",None,"element-desktop",
     "Matrix client for decentralised chat","Клиент Matrix для децентрализованных чатов"),
 ]),
 ("Media", "Мультимедиа", "media", [
   A("VLC","VLC media player","VideoLAN.VLC","vlc","vlc",
     "Plays practically every audio and video format","Проигрывает практически любые аудио и видео"),
   A("Spotify","Spotify","Spotify.Spotify","spotify","spotify",
     "Music and podcast streaming","Стриминг музыки и подкастов"),
   A("AIMP","AIMP","AIMP.AIMP","aimp","aimp",
     "Lightweight audio player with an equaliser","Лёгкий аудиоплеер с эквалайзером"),
   A("foobar2000","foobar2000","PeterPawlowski.foobar2000","foobar2000","foobar2000",
     "Minimal, highly configurable audio player","Минималистичный и гибкий аудиоплеер"),
   A("MPV","mpv","shinchiro.mpv","mpv","mpv.install",
     "Keyboard-driven video player with no clutter","Видеоплеер без лишнего интерфейса"),
   A("K_Lite","K-Lite Codec Pack","CodecGuide.K-LiteCodecPack.Standard",None,"k-litecodecpackstandard",
     "Codec pack for system-wide video playback","Набор кодеков для воспроизведения видео в системе"),
   A("OBS_Studio","OBS Studio","OBSProject.OBSStudio",None,"obs-studio",
     "Screen recording and live streaming","Запись экрана и трансляции"),
   A("Audacity","Audacity","Audacity.Audacity","audacity","audacity",
     "Free multi-track audio editor","Бесплатный многодорожечный аудиоредактор"),
   A("HandBrake","HandBrake","HandBrake.HandBrake","handbrake","handbrake",
     "Video converter with ready-made presets","Видеоконвертер с готовыми пресетами"),
   A("Shotcut","Shotcut","Meltytech.Shotcut","shotcut","shotcut",
     "Free cross-platform video editor","Бесплатный видеоредактор"),
 ]),
 ("Graphics", "Графика и дизайн", "image", [
   A("Krita","Krita","KDE.Krita","krita","krita",
     "Digital painting studio for artists","Студия цифровой живописи для художников"),
   A("GIMP","GIMP","GIMP.GIMP","gimp","gimp",
     "Full-featured raster image editor","Полноценный редактор растровой графики"),
   A("Inkscape","Inkscape","Inkscape.Inkscape","inkscape","inkscape",
     "Vector graphics editor for SVG","Редактор векторной графики SVG"),
   A("Paint_NET","paint.net","dotPDN.PaintDotNet","paint.net","paint.net",
     "Simple image editor with layers","Простой редактор изображений со слоями"),
   A("Blender","Blender","BlenderFoundation.Blender","blender","blender",
     "3D modelling, animation and rendering","3D-моделирование, анимация и рендеринг"),
   A("Figma","Figma","Figma.Figma",None,"figma",
     "Collaborative interface design","Совместное проектирование интерфейсов"),
   A("IrfanView","IrfanView","IrfanSkiljan.IrfanView","irfanview","irfanview",
     "Very fast image viewer and converter","Очень быстрый просмотрщик и конвертер изображений"),
   A("XnView_MP","XnView MP","XnSoft.XnViewMP","xnviewmp","xnviewmp",
     "Image browser supporting 500+ formats","Просмотрщик с поддержкой 500+ форматов"),
   A("ShareX","ShareX","ShareX.ShareX","sharex","sharex",
     "Screenshots and screen recording with upload","Скриншоты и запись экрана с загрузкой в сеть"),
   A("Greenshot","Greenshot","Greenshot.Greenshot","greenshot","greenshot",
     "Lightweight screenshot tool with an editor","Лёгкий инструмент для скриншотов с редактором"),
   A("Lightshot","Lightshot","Skillbrains.Lightshot",None,"lightshot",
     "Instant screenshots of any screen area","Мгновенные скриншоты любой области экрана"),
 ]),
 ("Documents", "Документы", "doc", [
   A("LibreOffice","LibreOffice","TheDocumentFoundation.LibreOffice","libreoffice","libreoffice-fresh",
     "Free office suite: text, sheets, slides","Бесплатный офис: текст, таблицы, презентации"),
   A("ONLYOFFICE","ONLYOFFICE","ONLYOFFICE.DesktopEditors",None,"onlyoffice",
     "Office suite with strong MS Office fidelity","Офисный пакет с хорошей совместимостью с MS Office"),
   A("Acrobat_Reader","Adobe Acrobat Reader","Adobe.Acrobat.Reader.64-bit",None,"adobereader",
     "The reference PDF reader","Эталонный просмотрщик PDF"),
   A("Foxit_Reader","Foxit Reader","Foxit.FoxitReader","foxit-reader","foxitreader",
     "Fast PDF reader with annotations","Быстрый просмотрщик PDF с аннотациями"),
   A("SumatraPDF","SumatraPDF","SumatraPDF.SumatraPDF","sumatrapdf","sumatrapdf",
     "Tiny reader for PDF, EPUB and comics","Крошечная читалка PDF, EPUB и комиксов"),
   A("PDF24","PDF24 Creator","geeksoftwareGmbH.PDF24Creator",None,"pdf24",
     "Merge, split and convert PDF files","Объединение, разделение и конвертация PDF"),
   A("Obsidian","Obsidian","Obsidian.Obsidian","obsidian","obsidian",
     "Markdown notes stored as local files","Заметки в Markdown, хранящиеся локально"),
   A("Notion","Notion","Notion.Notion","notion","notion",
     "Notes, wiki and tasks in one workspace","Заметки, вики и задачи в одном месте"),
   A("Evernote","Evernote","Evernote.Evernote","evernote","evernote",
     "Notes, web clippings and reminders","Заметки, вырезки из веба и напоминания"),
   A("Calibre","calibre","calibre.calibre","calibre","calibre",
     "E-book library manager and converter","Менеджер и конвертер электронных книг"),
   A("Anki","Anki","Anki.Anki","anki","anki",
     "Spaced-repetition flashcards","Карточки для запоминания по интервальному методу"),
 ]),
 ("Gaming", "Игры", "game", [
   A("Steam","Steam","Valve.Steam","steam","steam",
     "The biggest PC game store and launcher","Крупнейший магазин и лаунчер игр для ПК"),
   A("Epic_Games","Epic Games","EpicGames.EpicGamesLauncher","epic-games-launcher","epicgameslauncher",
     "Epic store with weekly free games","Магазин Epic с еженедельными бесплатными играми"),
   A("EA_App","EA App","ElectronicArts.EADesktop",None,"ea-app",
     "Launcher for Electronic Arts games","Лаунчер для игр Electronic Arts"),
   A("GOG_Galaxy","GOG Galaxy","GOG.Galaxy",None,"goggalaxy",
     "DRM-free store that unifies your libraries","Магазин без DRM, объединяющий библиотеки"),
   A("Ubisoft_Connect","Ubisoft Connect","Ubisoft.Connect",None,"ubisoft-connect",
     "Launcher for Ubisoft games","Лаунчер для игр Ubisoft"),
   A("Battle_net","Battle.net","Blizzard.BattleNet",None,"battle.net",
     "Launcher for Blizzard games","Лаунчер для игр Blizzard"),
   A("MSI_Afterburner","MSI Afterburner","Guru3D.Afterburner",None,"msiafterburner",
     "GPU tuning and in-game monitoring","Разгон видеокарты и мониторинг в играх"),
 ]),
 ("Files", "Файлы и облако", "cloud", [
   A("qBittorrent","qBittorrent","qBittorrent.qBittorrent","qbittorrent","qbittorrent",
     "Ad-free torrent client","Торрент-клиент без рекламы"),
   A("Google_Drive","Google Drive","Google.GoogleDrive","googledrive","googledrive",
     "Google cloud storage with desktop sync","Облако Google с синхронизацией на ПК"),
   A("OneDrive","OneDrive","Microsoft.OneDrive",None,"onedrive",
     "Microsoft cloud storage","Облачное хранилище Microsoft"),
   A("Dropbox","Dropbox","Dropbox.Dropbox","dropbox","dropbox",
     "Classic file sync across devices","Классическая синхронизация файлов между устройствами"),
   A("Yandex_Disk","Yandex.Disk","Yandex.Disk",None,"yandex-disk",
     "Yandex cloud storage","Облачное хранилище Яндекса"),
   A("Quick_Share","Quick Share","Google.QuickShare",None,None,
     "Send files between Windows and Android","Передача файлов между Windows и Android"),
   A("Total_Commander","Total Commander","Ghisler.TotalCommander",None,"totalcommander",
     "Two-pane file manager, the classic","Классический двухпанельный файловый менеджер"),
   A("FileZilla","FileZilla",None,"filezilla","filezilla",
     "FTP, FTPS and SFTP client","Клиент FTP, FTPS и SFTP"),
   A("WinSCP","WinSCP","WinSCP.WinSCP","winscp","winscp",
     "SFTP/SCP transfers with a dual-pane UI","Передача по SFTP/SCP в двухпанельном окне"),
   A("Cyberduck","Cyberduck","Iterate.Cyberduck",None,"cyberduck",
     "Browse cloud and FTP storage like folders","Доступ к облакам и FTP как к папкам"),
 ]),
 ("Utilities", "Утилиты", "tools", [
   A("Everything","Everything","voidtools.Everything","everything","everything",
     "Instant file search by name","Мгновенный поиск файлов по имени"),
   A("PowerToys","Microsoft PowerToys","Microsoft.PowerToys",None,"powertoys",
     "Window, launcher and utility pack for Windows","Набор утилит для окон, поиска и не только"),
   A("Windows_Terminal","Windows Terminal","Microsoft.WindowsTerminal",None,"microsoft-windows-terminal",
     "Modern tabbed terminal for Windows","Современный терминал с вкладками"),
   A("TeamViewer","TeamViewer","TeamViewer.TeamViewer","teamviewer","teamviewer",
     "Remote access and support","Удалённый доступ и поддержка"),
   A("AnyDesk","AnyDesk","AnyDesk.AnyDesk","anydesk","anydesk",
     "Lightweight, low-latency remote desktop","Лёгкий удалённый рабочий стол с низкой задержкой"),
   G("RealVNC","RealVNC",
     "Remote desktop over the VNC protocol","Удалённый рабочий стол по протоколу VNC",
     [("Server","RealVNC.VNCServer",None,"vnc-server"),
      ("Viewer","RealVNC.VNCViewer","vnc-viewer","vnc-viewer")]),
   A("TightVNC","TightVNC","GlavSoft.TightVNC","tightvnc","tightvnc",
     "Free VNC server and viewer","Бесплатный VNC-сервер и клиент"),
   A("TeraCopy","TeraCopy","CodeSector.TeraCopy","teracopy","teracopy",
     "Faster file copying with verification","Быстрое копирование файлов с проверкой"),
   A("Revo","Revo Uninstaller","RevoUninstaller.RevoUninstaller","revo-uninstaller","revo-uninstaller",
     "Uninstall programs and clean the leftovers","Удаление программ вместе с их следами"),
   A("WizTree","WizTree","AntibodySoftware.WizTree","wiztree","wiztree",
     "Find what fills your disk in seconds","Находит, что занимает диск, за секунды"),
   A("CCleaner","CCleaner","Piriform.CCleaner","ccleaner","ccleaner",
     "Clean temporary files and the registry","Очистка временных файлов и реестра"),
   A("Rufus","Rufus","Rufus.Rufus","rufus","rufus",
     "Make bootable USB drives","Создание загрузочных USB-накопителей"),
   A("Ditto","Ditto","Ditto.Ditto","ditto","ditto",
     "Clipboard history manager","Менеджер истории буфера обмена"),
   A("CrystalDiskInfo","CrystalDiskInfo","CrystalDewWorld.CrystalDiskInfo","crystaldiskinfo","crystaldiskinfo",
     "S.M.A.R.T. health monitoring for drives","Мониторинг здоровья дисков по S.M.A.R.T."),
   A("HWiNFO","HWiNFO","REALiX.HWiNFO","hwinfo","hwinfo",
     "Detailed hardware info and sensors","Подробная информация о железе и датчиках"),
   A("CPU_Z","CPU-Z","CPUID.CPU-Z","cpu-z","cpu-z",
     "CPU, memory and board identification","Определение процессора, памяти и платы"),
 ]),
 ("Compression", "Архиваторы", "archive", [
   A("7-Zip","7-Zip","7zip.7zip","7zip","7zip",
     "Free archiver with the best compression","Бесплатный архиватор с лучшим сжатием"),
   A("NanaZip","NanaZip","M2Team.NanaZip",None,"nanazip",
     "Modern 7-Zip fork with Windows 11 menus","Современный форк 7-Zip с меню Windows 11"),
   A("WinRAR","WinRAR","RARLab.WinRAR",None,"winrar",
     "The RAR format archiver","Архиватор формата RAR"),
   A("PeaZip","PeaZip","Giorgiotani.Peazip","peazip","peazip",
     "Open-source archiver with strong encryption","Открытый архиватор с надёжным шифрованием"),
 ]),
 ("Security", "Безопасность", "shield", [
   A("Bitwarden","Bitwarden","Bitwarden.Bitwarden","bitwarden","bitwarden",
     "Password manager with cloud sync","Менеджер паролей с облачной синхронизацией"),
   A("KeePassXC","KeePassXC","KeePassXCTeam.KeePassXC","keepassxc","keepassxc",
     "Offline password vault in a local file","Офлайн-хранилище паролей в локальном файле"),
   A("KeePass_2","KeePass 2","DominikReichl.KeePass","keepass","keepass",
     "The original KeePass password manager","Оригинальный менеджер паролей KeePass"),
   A("Malwarebytes","Malwarebytes","Malwarebytes.Malwarebytes",None,"malwarebytes",
     "On-demand malware scanner and cleaner","Сканер и чистильщик вредоносного ПО"),
   A("Proton_VPN","Proton VPN","Proton.ProtonVPN",None,"protonvpn",
     "VPN with an audited no-logs policy","VPN с проверенной политикой отсутствия логов"),
 ]),
 ("Developer Tools", "Для разработчиков", "code", [
   A("Visual_Studio_Code","Visual Studio Code","Microsoft.VisualStudioCode","vscode","vscode",
     "The most popular extensible code editor","Самый популярный расширяемый редактор кода"),
   A("Cursor","Cursor","Anysphere.Cursor","cursor",None,
     "AI-first code editor built on VS Code","AI-редактор кода на базе VS Code"),
   A("Notepad++","Notepad++","Notepad++.Notepad++","notepadplusplus","notepadplusplus",
     "Lightweight editor for quick edits","Лёгкий редактор для быстрых правок"),
   A("Sublime_Text","Sublime Text","SublimeHQ.SublimeText.4","sublime-text","sublimetext4",
     "Very fast editor with multiple cursors","Очень быстрый редактор с мультикурсором"),
   A("Git","Git","Git.Git","git","git",
     "The version control system","Система контроля версий"),
   A("GitHub_Desktop","GitHub Desktop","GitHub.GitHubDesktop",None,"github-desktop",
     "Visual Git client for GitHub","Визуальный Git-клиент для GitHub"),
   A("Python_3","Python 3","Python.Python.3.13","python","python3",
     "Python interpreter and pip","Интерпретатор Python и pip"),
   A("NodeJS","Node.js LTS","OpenJS.NodeJS.LTS","nodejs-lts","nodejs-lts",
     "JavaScript runtime with npm","Среда выполнения JavaScript с npm"),
   A("PowerShell_7","PowerShell 7","Microsoft.PowerShell","pwsh","powershell-core",
     "Cross-platform PowerShell, the modern one","Современный кроссплатформенный PowerShell"),
   A("Docker_Desktop","Docker Desktop","Docker.DockerDesktop",None,"docker-desktop",
     "Containers on Windows via WSL 2","Контейнеры в Windows через WSL 2"),
   A("DBeaver","DBeaver","DBeaver.DBeaver.Community","dbeaver","dbeaver",
     "Universal database client","Универсальный клиент баз данных"),
   A("Postman","Postman","Postman.Postman","postman","postman",
     "API testing and collections","Тестирование API и коллекции запросов"),
   A("PuTTY","PuTTY","PuTTY.PuTTY","putty","putty",
     "The classic SSH and serial client","Классический SSH- и serial-клиент"),
   A("WinMerge","WinMerge","WinMerge.WinMerge","winmerge","winmerge",
     "Compare and merge files and folders","Сравнение и слияние файлов и папок"),
   A("Wireshark","Wireshark","WiresharkFoundation.Wireshark",None,"wireshark",
     "Network protocol analyser","Анализатор сетевых протоколов"),
   A("VirtualBox","Oracle VirtualBox","Oracle.VirtualBox",None,"virtualbox",
     "Free desktop virtualisation","Бесплатная виртуализация на ПК"),
 ]),
 (".NET", ".NET", "runtime", [
   G(".NET_Desktop_Runtime",".NET Desktop Runtime",
     "Runtime required by WPF and WinForms apps","Среда выполнения для приложений WPF и WinForms",
     [("8 (x64)","Microsoft.DotNet.DesktopRuntime.8",None,"dotnet-8.0-desktopruntime"),
      ("9 (x64)","Microsoft.DotNet.DesktopRuntime.9",None,"dotnet-9.0-desktopruntime"),
      ("10 (x64)","Microsoft.DotNet.DesktopRuntime.10",None,"dotnet-10.0-desktopruntime")]),
   G("ASP.NET_Core_Runtime","ASP.NET Core Runtime",
     "Runtime required by ASP.NET Core web apps","Среда выполнения для веб-приложений ASP.NET Core",
     [("8 (x64)","Microsoft.DotNet.AspNetCore.8",None,"dotnet-8.0-aspnetruntime"),
      ("9 (x64)","Microsoft.DotNet.AspNetCore.9",None,"dotnet-9.0-aspnetruntime"),
      ("10 (x64)","Microsoft.DotNet.AspNetCore.10",None,"dotnet-10.0-aspnetruntime")]),
   G(".NET_SDK",".NET SDK",
     "Full SDK for building .NET applications","Полный SDK для разработки приложений .NET",
     [("8","Microsoft.DotNet.SDK.8",None,"dotnet-8.0-sdk"),
      ("9","Microsoft.DotNet.SDK.9",None,"dotnet-9.0-sdk"),
      ("10","Microsoft.DotNet.SDK.10",None,"dotnet-10.0-sdk")]),
   A(".NET_Framework_4.8.1",".NET Framework 4.8.1 Dev Pack","Microsoft.DotNet.Framework.DeveloperPack_4",None,"netfx-4.8.1-devpack",
     "Targeting pack for building .NET Framework apps","Пакет разработки под .NET Framework"),
 ]),
 ("Java", "Java", "runtime", [
   G("Temurin_JRE","Eclipse Temurin JRE",
     "Free Java runtime for desktop apps","Бесплатная среда выполнения Java для программ",
     [("8 (x64)","EclipseAdoptium.Temurin.8.JRE","temurin8-jre","temurin8jre"),
      ("11 (x64)","EclipseAdoptium.Temurin.11.JRE","temurin11-jre","temurin11jre"),
      ("17 (x64)","EclipseAdoptium.Temurin.17.JRE","temurin17-jre","temurin17jre"),
      ("21 (x64)","EclipseAdoptium.Temurin.21.JRE","temurin21-jre","temurin21jre")]),
   G("Corretto_JDK","Amazon Corretto JDK",
     "Amazon's supported OpenJDK build","Сборка OpenJDK с поддержкой от Amazon",
     [("8 (x64)","Amazon.Corretto.8.JDK","corretto8-jdk","corretto8jdk"),
      ("11 (x64)","Amazon.Corretto.11.JDK","corretto11-jdk","corretto11jdk"),
      ("17 (x64)","Amazon.Corretto.17.JDK","corretto17-jdk","corretto17jdk"),
      ("21 (x64)","Amazon.Corretto.21.JDK","corretto21-jdk","corretto21jdk")]),
   G("Microsoft_OpenJDK","Microsoft Build of OpenJDK",
     "Microsoft's OpenJDK build with Hotspot","Сборка OpenJDK от Microsoft с Hotspot",
     [("17","Microsoft.OpenJDK.17",None,"microsoft-openjdk17"),
      ("21","Microsoft.OpenJDK.21",None,"microsoft-openjdk21")]),
 ]),
 ("VC++ Redistributables", "Библиотеки VC++", "runtime", [
   G("VC_Redist_2015_","Visual C++ 2015-2022",
     "Runtime libraries required by most modern apps","Библиотеки, нужные большинству современных программ",
     [("x64","Microsoft.VCRedist.2015+.x64",None,"vcredist140"),
      ("x86","Microsoft.VCRedist.2015+.x86",None,"vcredist140")]),
   G("VC_Redist_2013","Visual C++ 2013",
     "Runtime libraries for older applications","Библиотеки для более старых программ",
     [("x64","Microsoft.VCRedist.2013.x64",None,"vcredist2013"),
      ("x86","Microsoft.VCRedist.2013.x86",None,"vcredist2013")]),
   G("VC_Redist_2012","Visual C++ 2012",
     "Runtime libraries for older applications","Библиотеки для более старых программ",
     [("x64","Microsoft.VCRedist.2012.x64",None,"vcredist2012"),
      ("x86","Microsoft.VCRedist.2012.x86",None,"vcredist2012")]),
   G("VC_Redist_2010","Visual C++ 2010",
     "Runtime libraries for legacy applications","Библиотеки для устаревших программ",
     [("x64","Microsoft.VCRedist.2010.x64",None,"vcredist2010"),
      ("x86","Microsoft.VCRedist.2010.x86",None,"vcredist2010")]),
   G("VC_Redist_2008","Visual C++ 2008",
     "Runtime libraries for legacy applications","Библиотеки для устаревших программ",
     [("x64","Microsoft.VCRedist.2008.x64",None,"vcredist2008"),
      ("x86","Microsoft.VCRedist.2008.x86",None,"vcredist2008")]),
 ]),
]

# Frequently installed on a fresh Windows box, in install order.
POPULAR = [
 "Chrome","Firefox","Telegram","Discord","VLC","Spotify",
 "7-Zip","WinRAR","Everything","PowerToys","Steam","qBittorrent",
 "Notepad++","Visual_Studio_Code","Git","Acrobat_Reader","Bitwarden","AnyDesk",
]
# Runtime groups that belong to the "popular" quick pick, as (group key, variant label).
POPULAR_VARIANTS = [
 ("VC_Redist_2015_","x64"),
 (".NET_Desktop_Runtime","8 (x64)"),
]
