# -*- coding: utf-8 -*-
"""Generates Catalog.Data.cs from catalog.py."""
import os, re, catalog

ICONS = {os.path.splitext(f)[0] for f in os.listdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Icons"))}
ICON_OVERRIDES = {
    "Temurin_JRE": "Java__AdoptOpenJDK__8",
    "Corretto_JDK": "JDK__Amazon_Corretto__8",
    "Microsoft_OpenJDK": "Java__AdoptOpenJDK__8",
    "VC_Redist_2015_": "VC_Redist_x64_2015_",
    "VC_Redist_2013": "VC_Redist_x64_2013",
    "VC_Redist_2012": "VC_Redist_x64_2012",
    "VC_Redist_2010": "VC_Redist_x64_2010",
    "VC_Redist_2008": "VC_Redist_x64_2008",
    "RealVNC": "RealVNC_Server",
}

def sanitize(key):
    return re.sub(r"[^a-zA-Z0-9_\-.]", "_", key)

def icon_for(key):
    name = ICON_OVERRIDES.get(key, sanitize(key))
    return name if name in ICONS else None

def cs(v):
    if v is None:
        return "null"
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'

def pkg(winget, scoop, choco):
    return f"new PackageRef({cs(winget)}, {cs(scoop)}, {cs(choco)})"

out = []
w = out.append
w("// <auto-generated>")
w("//     Generated from tools/catalog.py. Every winget id in this file was checked")
w("//     against the official winget source index before being committed.")
w("//     Do not edit by hand: regenerate with `python3 tools/gen_catalog.py`.")
w("// </auto-generated>")
w("")
w("using System.Collections.Generic;")
w("")
w("namespace HyperionWPF.Model")
w("{")
w("    internal static partial class Catalog")
w("    {")
w("        private static IReadOnlyList<Category> BuildCategories() => new[]")
w("        {")

used_icons = set()
for name_en, name_ru, glyph, apps in catalog.CATEGORIES:
    w(f"            new Category({cs(name_en)}, {cs(name_en)}, {cs(name_ru)}, CategoryGlyph.{glyph.capitalize()}, new[]")
    w("            {")
    for a in apps:
        icon = icon_for(a["key"])
        if icon:
            used_icons.add(icon)
        head = (f"                new AppEntry({cs(a['key'])}, {cs(a['title'])}, {cs(icon)}, "
                f"{cs(a['en'])}, {cs(a['ru'])}, ")
        if a["kind"] == "app":
            w(head + pkg(a["winget"], a["scoop"], a["choco"]) + "),")
        else:
            w(head + "new[]")
            w("                {")
            for label, wi, sc, ch in a["variants"]:
                w(f"                    new AppVariant({cs(label)}, {pkg(wi, sc, ch)}),")
            w("                }),")
    w("            }),")
w("        };")
w("")
w("        private static readonly string[] PopularKeys =")
w("        {")
for k in catalog.POPULAR:
    w(f"            {cs(k)},")
w("        };")
w("")
w("        private static readonly (string Key, string Variant)[] PopularVariants =")
w("        {")
for k, v in catalog.POPULAR_VARIANTS:
    w(f"            ({cs(k)}, {cs(v)}),")
w("        };")
w("    }")
w("}")

open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Model", "Catalog.Data.cs"), "w", encoding="utf-8-sig").write("\n".join(out) + "\n")
print("entries:", sum(len(c[3]) for c in catalog.CATEGORIES))
print("icons used:", len(used_icons), "of", len(ICONS))
print("unused icon files:", sorted(ICONS - used_icons))
